// Mock API layer for the JengaVest demo.
//
// This is a front-end / design demo — there is no live backend. These
// functions simulate a small amount of network latency and return canned
// data so the whole UI can be explored end-to-end without a server.
// Swapping these out for real `fetch` calls is all it would take to wire
// up a backend later.

import { Message } from '@/types';

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

export interface ChatContext {
  value: number;
  invested: number;
  dayGainUsd: number;
  dayGainPct: number;
  holdings: { ticker: string; currentValue: number; change: number }[];
}

const wait = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

const usd = (n: number) =>
  n.toLocaleString('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });

const CANNED_REPLIES: { match: RegExp; reply: string }[] = [
  {
    match: /portfolio|performing|doing today|overview/i,
    reply:
      'Your demo portfolio is worth $24,381, up $571 (+2.4%) today. Equities are driving the gain — Apple (+1.8%) and Microsoft (+2.1%) are your strongest holdings, while Bitcoin is down 0.8%. Overall risk looks moderate given a 26% bond allocation.',
  },
  {
    match: /apple|aapl/i,
    reply:
      'Apple (AAPL) is trading at $189.42 in this demo, up 1.8% on the day. It makes up roughly 15% of the sample portfolio.',
  },
  {
    match: /rebalanc/i,
    reply:
      'Your sample allocation is 40% stocks, 20% ETFs, 14% crypto and 26% bonds. That is reasonably balanced for a moderate risk profile. If you wanted to reduce volatility you could trim the crypto sleeve toward bonds — but this is illustrative demo data, not financial advice.',
  },
  {
    match: /tesla|tsla/i,
    reply:
      'This is a demo, so I do not have live Tesla data. In the full concept, the analyst would pull the latest quote and recent headlines and summarise them here with citations.',
  },
  {
    match: /risk/i,
    reply:
      'The biggest concentration in the sample portfolio is the 14% crypto allocation, which carries the most day-to-day volatility. Bonds (26%) act as ballast. Overall the demo risk score is "Moderate".',
  },
];

const FALLBACK_REPLY =
  'Thanks for the question! This is a UI demo, so responses are simulated rather than generated by a live model. Try one of the suggested questions to see a sample analyst reply.';

function portfolioReply(message: string, ctx: ChatContext): string | null {
  if (ctx.holdings.length === 0) {
    if (/portfolio|performing|doing|holding|risk|rebalanc/i.test(message)) {
      return 'Your portfolio is empty right now. Head to the Markets page, search for a stock, and add how much you invested — then I can break down your performance here.';
    }
    return null;
  }

  if (/portfolio|performing|doing today|overview|total/i.test(message)) {
    const sign = ctx.dayGainUsd >= 0 ? 'up' : 'down';
    const top = [...ctx.holdings].sort((a, b) => b.currentValue - a.currentValue)[0];
    return `Your portfolio is worth ${usd(ctx.value)} across ${ctx.holdings.length} holding${ctx.holdings.length > 1 ? 's' : ''}, ${sign} ${usd(Math.abs(ctx.dayGainUsd))} (${ctx.dayGainPct.toFixed(2)}%) today. Your largest position is ${top.ticker} at ${usd(top.currentValue)}. You've invested ${usd(ctx.invested)} in total.`;
  }

  if (/risk|biggest|concentrat/i.test(message)) {
    const top = [...ctx.holdings].sort((a, b) => b.currentValue - a.currentValue)[0];
    const pct = ctx.value > 0 ? (top.currentValue / ctx.value) * 100 : 0;
    return `Your biggest concentration is ${top.ticker}, about ${pct.toFixed(0)}% of the portfolio. Single positions above ~20% add concentration risk — spreading across more names or sectors would reduce it. (Demo insight, not financial advice.)`;
  }

  if (/best|worst|mover|gain|loser/i.test(message)) {
    const best = [...ctx.holdings].sort((a, b) => b.change - a.change)[0];
    const worst = [...ctx.holdings].sort((a, b) => a.change - b.change)[0];
    return `Today's best mover is ${best.ticker} (${best.change >= 0 ? '+' : ''}${best.change.toFixed(1)}%) and the weakest is ${worst.ticker} (${worst.change >= 0 ? '+' : ''}${worst.change.toFixed(1)}%).`;
  }

  return null;
}

export async function sendMockMessage(
  message: string,
  _history: Message[],
  ctx?: ChatContext,
): Promise<{ response: string }> {
  await wait(500 + Math.random() * 700);
  if (ctx) {
    const dynamic = portfolioReply(message, ctx);
    if (dynamic) return { response: dynamic };
  }
  const hit = CANNED_REPLIES.find((c) => c.match.test(message));
  return { response: hit ? hit.reply : FALLBACK_REPLY };
}

export async function uploadMockDocument(_file: File): Promise<{ status: 'indexed' }> {
  // Simulate an indexing step; nothing leaves the browser.
  await wait(1200);
  return { status: 'indexed' };
}

// ── Real backend chat ─────────────────────────────────────────────────────

export interface ChatResult {
  response: string;
  citations: string[];
  offline: boolean;
}

/**
 * Send a message to the real JengaVest backend (/chat). A portfolio preamble
 * is prepended so the analyst discusses only the user's current holdings.
 * If the backend is unreachable or slow to wake, falls back to the local
 * portfolio-aware mock so the chat always responds.
 */
export async function sendChat(
  rawText: string,
  history: Message[],
  opts: { preamble?: string; ctx?: ChatContext } = {},
): Promise<ChatResult> {
  const message = opts.preamble ? `${opts.preamble}\n\nUser question: ${rawText}` : rawText;

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 75000);
  try {
    const res = await fetch(`${API_URL}/chat`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        message,
        conversation_history: history.map((m) => ({ role: m.role, content: m.content })),
      }),
      signal: controller.signal,
    });
    clearTimeout(timer);
    if (res.ok) {
      const data = await res.json();
      return {
        response: data.response ?? '',
        citations: data.citations ?? [],
        offline: false,
      };
    }
  } catch {
    /* backend unreachable or timed out — fall back to mock */
  }
  clearTimeout(timer);

  const mock = await sendMockMessage(rawText, history, opts.ctx);
  return { response: mock.response, citations: [], offline: true };
}

/**
 * Streaming version of sendChat. POSTs to /chat/stream and calls `onDelta`
 * with each text chunk as it arrives. Falls back to the non-streaming path
 * (which itself falls back to the mock) if streaming is unavailable.
 */
export async function streamChat(
  rawText: string,
  history: Message[],
  opts: { preamble?: string; ctx?: ChatContext } = {},
  onDelta: (chunk: string) => void = () => {},
): Promise<{ citations: string[]; offline: boolean }> {
  const message = opts.preamble ? `${opts.preamble}\n\nUser question: ${rawText}` : rawText;
  let gotAny = false;

  try {
    const res = await fetch(`${API_URL}/chat/stream`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        message,
        conversation_history: history.map((m) => ({ role: m.role, content: m.content })),
      }),
    });
    if (!res.ok || !res.body) throw new Error('no stream');

    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let buffer = '';
    let citations: string[] = [];

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const parts = buffer.split('\n\n');
      buffer = parts.pop() ?? '';
      for (const part of parts) {
        const line = part.trim();
        if (!line.startsWith('data:')) continue;
        const payload = line.slice(5).trim();
        if (!payload) continue;
        let evt: { type?: string; text?: string; citations?: string[]; message?: string };
        try { evt = JSON.parse(payload); } catch { continue; }
        if (evt.type === 'delta' && evt.text) { gotAny = true; onDelta(evt.text); }
        else if (evt.type === 'sources') citations = evt.citations || [];
        else if (evt.type === 'error' && !gotAny) throw new Error(evt.message || 'stream error');
      }
    }
    if (!gotAny) throw new Error('empty stream');
    return { citations, offline: false };
  } catch {
    const r = await sendChat(rawText, history, opts);
    if (!gotAny) onDelta(r.response);
    return { citations: r.citations, offline: r.offline };
  }
}
